### PR TITLE
[FIX] Fix invalid pet tracer in clinica command

### LINKED ISSUE #22: Invalid tracer
https://github.com/aramis-lab/clinicadl_handbook/blob/84e3a97c25954a2f511e59336a0ebdf1f616fecf/src/preprocessing.py#L342

returns the error 

`Error: Invalid value for '{11CPIB|18FAV1451|18FAV45|18FFBB|18FFDG|18FFMM}': 'fdg' is not one of <Tracer.PIB: '11CPIB'>, <Tracer.AV1451: '18FAV1451'>, <Tracer.AV45: '18FAV45'>, <Tracer.FBB: '18FFBB'>, <Tracer.FDG: '18FFDG'>, <Tracer.FMM: '18FFMM'>.`

And when I change `fdg` to `18FFDG`, I have an error like `* (sub-ADNI005S0610 | ses-M00): No file found`. My hypothesis is that it comes from the names of the PET files in the BIDS folder: maybe `sub-ADNI005S0610_ses-M00_task-rest_trc-fdg_pet.nii.gz` should be turned into `sub-ADNI005S0610_ses-M00_task-rest_trc-18FFDG_pet.nii.gz`?

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Fixes #22 

Files on the AramisLab server have been updated as well to have:

- 3 digits session labels
- pet tracers respecting the BIDS naming convention

@thibaultdvx could you try re-running the tutorial to see if it fixes the issue you originally had ?

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
@thibaultdvx Thanks for the review !

>>> No folder named data_adniis created.

Indeed, my bad... I fixed it on the server. If you download the archive again, it should decompress within a data_adni folder.

For the message that you get, I'm really not sure. 🤔 
Maybe try `tar -xvzf BIDS_example.tar.gz` to see what output you get.

**Comment by thibaultdvx** [comment]
@NicolasGensollen 

- I managed to run successfully the `pet-linear` with the updates you made on the names of the BIDS files.
- The folder is now decompressed within a `data_adni` folder.
- When I run `tar -xvzf BIDS_example.tar.gz`, I get:
  ```
  data_adni/
  data_adni/BIDS_example/
  data_adni/BIDS_example/sub-ADNI005S0610/
  data_adni/BIDS_example/sub-ADNI005S0929/
  data_adni/BIDS_example/sub-ADNI005S0929/ses-M000/
  data_adni/BIDS_example/sub-ADNI005S0929/sub-ADNI005S0929_sessions.tsv
  data_adni/BIDS_example/sub-ADNI005S0929/ses-M000/anat/
  data_adni/BIDS_example/sub-ADNI005S0929/ses-M000/pet/
  data_adni/BIDS_example/sub-ADNI005S0929/ses-M000/sub-ADNI005S0929_ses-M000_scans.tsv
  data_adni/BIDS_example/sub-ADNI005S0929/ses-M000/pet/sub-ADNI005S0929_ses-M000_task-rest_trc-18FFDG_pet.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0929/ses-M000/anat/sub-ADNI005S0929_ses-M000_T1w.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M000/
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M024/
  data_adni/BIDS_example/sub-ADNI005S0610/._ses-M048
  tar: Le mot clé inconnu « SCHILY.fflags » pour l'en-tête étendu a été ignoré
  tar: Le mot clé inconnu « LIBARCHIVE.xattr.com.apple.FinderInfo » pour l'en-tête étendu a été ignoré
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M048/
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M072/
  data_adni/BIDS_example/sub-ADNI005S0610/sub-ADNI005S0610_sessions.tsv
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M072/anat/
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M072/pet/
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M072/sub-ADNI005S0610_ses-M072_scans.tsv
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M072/pet/sub-ADNI005S0610_ses-M072_task-rest_trc-18FAV45_pet.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M072/pet/sub-ADNI005S0610_ses-M072_task-rest_trc-18FFDG_pet.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M072/anat/sub-ADNI005S0610_ses-M072_T1w.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M048/sub-ADNI005S0610_ses-M048_scans.tsv
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M048/anat/
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M048/pet/
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M048/pet/sub-ADNI005S0610_ses-M048_task-rest_trc-18FFDG_pet.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M048/pet/sub-ADNI005S0610_ses-M048_task-rest_trc-18FAV45_pet.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M048/anat/sub-ADNI005S0610_ses-M048_T1w.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M024/anat/
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M024/pet/
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M024/sub-ADNI005S0610_ses-M024_scans.tsv
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M024/pet/sub-ADNI005S0610_ses-M024_task-rest_trc-18FFDG_pet.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M024/anat/sub-ADNI005S0610_ses-M024_T1w.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M000/sub-ADNI005S0610_ses-M000_scans.tsv
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M000/anat/
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M000/pet/
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M000/pet/sub-ADNI005S0610_ses-M000_task-rest_trc-18FFDG_pet.nii.gz
  data_adni/BIDS_example/sub-ADNI005S0610/ses-M000/anat/sub-ADNI005S0610_ses-M000_T1w.nii.gz
  ```
- Finally, I think we need to add one last modification to close this issue (I already tested the code):
  https://github.com/aramis-lab/clinicadl_handbook/blob/18aba4d66288bc48a6c0fe4c82de99013a51ed51/src/preprocessing.py#L360-L366
  should be replaced with:
  ```
  suffix_caps = '_task-rest_trc-18FFDG_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_suvr-cerebellumPons2_pet.nii.gz'
  suffix_bids = '_task-rest_trc-18FFDG_pet.nii.gz'
  sub1 = 'data_adni/BIDS_example/sub-ADNI005S0610/ses-M072/pet/sub-ADNI005S0610_ses-M072' + suffix_bids 
  sub2 = 'data_adni/CAPS_example/subjects/sub-ADNI005S0610/ses-M072/pet_linear/sub-ADNI005S0610_ses-M072' + suffix_caps
  
  sub3 = 'data_adni/BIDS_example/sub-ADNI005S0929/ses-M000/pet/sub-ADNI005S0929_ses-M000' + suffix_bids
  sub4 = 'data_adni/CAPS_example/subjects/sub-ADNI005S0929/ses-M000/pet_linear/sub-ADNI005S0929_ses-M000' + suffix_caps
  ```

**Comment by thibaultdvx** [comment]
Regarding the last point, I noticed something a bit weird: if you look at `suffix_caps` closely, `fdg_pet_space` is replaced with `18FFDG_space`. It might seem irrelevant but when I run `clinicadl quality-check pet-linear data_adni/CAPS_example data_adni/QC_result_pet.tsv 18FFDG cerebellumPons2`, I get an error message like `* (sub-ADNI005S0610 | ses-M000): No file found`, which disappeared when I replaced `18FFDG_space` with `18FFDG_pet_space`. It makes me think that the `_pet_` part is important.

**Comment by NicolasGensollen** [comment]
Thanks for the review @thibaultdvx ! I made the changes you suggested in [669f185](https://github.com/aramis-lab/clinicadl_handbook/pull/23/commits/669f185fe5641bdf2d2db06ddec46516d4b788de)

Also, linking the issue you opened on ClinicaDL: https://github.com/aramis-lab/clinicadl/issues/538 on which this PR depends.

**Review by thibaultdvx — COMMENTED** [review]
Everything looks good to me!

**Pull request merged**
