### PR TITLE
Rewrite tsvtools section

### LINKED ISSUE #27: Clarification needed in tsvtools section
Several issues in this section that make it hardly understandable: 

1.  https://github.com/aramis-lab/clinicadl_handbook/blob/a1a56b20938bc683b6d1fa4d43e6ae9330e15730/src/label_extraction.py#L122-L129

    these lines don't show (supposedly fixed in #20, but not yet visible). Besides, it could be mentioned that it is OASIS1 that should be downloaded (and up to participant 107). And finally, I'm not even sure that it useful to ask the user to download the data, since they are not used in the section (unless the user wants to run the whole preprocessing pipeline on the whole dataset, which seems to be out of the scope of this handbook).
    <br />

1. https://github.com/aramis-lab/clinicadl_handbook/blob/a1a56b20938bc683b6d1fa4d43e6ae9330e15730/src/label_extraction.py#L133-L135

    If `oasis_after_qc.tsv` and `adni_after_qc.tsv` are outputs of `quality-check` procedure, they should be named `data_oasis/QC_result_t1.tsv` and `data_adni/QC_result_pet.tsv`, to be consistent with: 
    https://github.com/aramis-lab/clinicadl_handbook/blob/a1a56b20938bc683b6d1fa4d43e6ae9330e15730/src/preprocessing.py#L423-L428
    <br />

1. https://github.com/aramis-lab/clinicadl_handbook/blob/a1a56b20938bc683b6d1fa4d43e6ae9330e15730/src/label_extraction.py#L137-L139

    The user has the possibility to download the outputs of `merge-tsv` and `check-missing-modalities` procedures, but not the output of `quality-check` procedure. So, the procedure `get-labels` cannot be run properly with the `--restriction_tsv` option. Maybe it is what `oasis_after_qc.tsv` and `adni_after_qc.tsv` refer to, but I can't find them on the AramisLab server. 
    <br />

1. https://github.com/aramis-lab/clinicadl_handbook/blob/a1a56b20938bc683b6d1fa4d43e6ae9330e15730/src/label_extraction.py#L180
This command raises `Error: Missing argument 'OUTPUT_DIRECTORY'` because no directory for the output `.tsv` file is given.

### PR DESCRIPTION
**Pull request by thibaultdvx**
Fixes #27. Mainly focuses on the `get-labels` section to make it clearer. 

Sorry, the PR is polluted with a lot of changes in the ids of the cells of the notebooks (if you know how to build the notebooks without changing the ids, I would be happy to know that). Go directly to .py files to see the actual changes.

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
@thibaultdvx I think you can simply commit the Python files. The CI should take care of building the notebooks for us.

**Comment by thibaultdvx** [comment]
@NicolasGensollen yes indeed, I canceled the changes

**Comment by thibaultdvx** [comment]
@NicolasGensollen I think we're all set the merge, finally

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @thibaultdvx !
I trust your judgement for the coherence of the tutorial as a whole.

**Pull request merged**
